name: Maven and Docker Build

on:
  workflow_call:
    inputs:
      docker:
        type: boolean
        default: true

jobs:
  build:
    name: Maven and Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For Sonar blame information

      - name: Set up Java
        uses: actions/setup-java@v3 # v4 gets stuck in post setup
        with:
          java-version: "17"
          distribution: "liberica"
          cache: "maven"

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Verify with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify -B -P prod,coverage "-Dstyle.color=always" \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.organization=${{ github.repository_owner }} \
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}

      - name: Build Dockerfile (no push)
        if: ${{ inputs.docker == true || inputs.docker == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
