# Maven Build, Bump and Push to Docker Hub
name: Maven Build

on:
  workflow_call:
    inputs:
      docker:
        type: boolean
        default: true
      dockerhub_username:
        type: string
      image_name:
        type: string

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    environment: Build # To contain BUMP_PAT within an environment
    outputs:
      artifact_name: ${{ github.event.repository.name }}-${{ steps.semver.outputs.nextStrict }}
      new_tag: ${{ steps.semver.outputs.nextStrict }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUMP_PAT }}
          fetch-depth: 0 # For Sonar blame information

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "liberica"
          cache: "maven"

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Get Version Information
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          patchAll: true
          noVersionBumpBehavior: patch
          skipInvalidTags: true

      - name: Set Next Version # So app can be packaged with correct version
        run: mvn org.codehaus.mojo:versions-maven-plugin:set -DnewVersion=${{ steps.semver.outputs.nextStrict }}

      - name: Verify and Scan with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify -B -P prod,coverage "-Dstyle.color=always" \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.organization=${{ github.repository_owner }} \
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}

      - name: Commit, Tag and Push New Version
        id: bump
        uses: soat-tech-challenge/gh-action-bump-maven-version@main
        with:
          commit-message: "[skip ci] Bump version to"
          version: ${{ steps.semver.outputs.nextStrict }}

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.semver.outputs.nextStrict }}
          path: target/*.jar
          if-no-files-found: error

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.semver.outputs.nextStrict }}-coverage-report
          path: target/site/jacoco/*

  docker:
    name: Docker Build and Push
    if: ${{ inputs.docker == true || inputs.docker == 'true' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Docker Hub
      url: https://hub.docker.com/layers/${{ inputs.image_name }}/${{ needs.build.outputs.new_tag }}/images/${{ steps.docker_build_push.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.image_name }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ needs.build.outputs.new_tag }}
          labels: |
            org.opencontainers.image.authors=${{ github.event.repository.owner.html_url }}#group-members
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=https://hub.docker.com/r/${{ inputs.image_name }}
            org.opencontainers.image.documentation=${{ github.event.repository.html_url }}/wiki
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ needs.build.outputs.new_tag }}
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Build and push image
        id: docker_build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
