# Terraform API-driven apply run using Terraform Cloud
name: Terraform Apply

on:
  workflow_call:
    # See https://developer.hashicorp.com/terraform/cli/cloud/settings#environment-variables
    inputs:
      cloud_organization:
        type: string
        default: "soat-tech-challenge"
      cloud_workspace:
        type: string
      config_directory:
        type: string
        default: "./"

jobs:
  terraform_apply:
    name: Terraform Apply via Terraform Cloud API
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.cloud_workspace }}
      url: ${{ steps.apply-run.outputs.run_link }}

    outputs:
      status: ${{ steps.apply-run.outputs.status }}
      payload: ${{ steps.apply-run.outputs.payload }}
      run_id: ${{ steps.apply-run.outputs.id }}
      run_link: ${{ steps.apply-run.outputs.run_link }}
      plan_id: ${{ steps.apply-run.outputs.plan_id }}

    env:
      TF_CLOUD_ORGANIZATION: ${{ inputs.cloud_organization }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ inputs.cloud_workspace }}
      CONFIG_DIRECTORY: ${{ inputs.config_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.4
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
